DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS log;
DROP TABLE IF EXISTS pwreset;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT NOT NULL,
  country TEXT NOT NULL
);

CREATE TABLE log(
tid INTEGER PRIMARY KEY AUTOINCREMENT,
lifter_id INTEGER NOT NULL,
tday INTEGER  NOT NULL,
exercise TEXT NOT NULL,
weight INTEGER NOT NULL,
sets INTEGER NOT NULL,
reps INTEGER NOT NULL,
FOREIGN KEY (lifter_id) REFERENCES user (id)
);

CREATE TABLE pwreset (
id INTEGER PRIMARY KEY,
reset_key TEXT UNIQUE,
user_id INTEGER NOT NULL,
datetime TEXT DEFAULT CURRENT_TIMESTAMP,
has_activated INTEGER DEFAULT 0,
FOREIGN KEY (user_id) REFERENCES users(id)
);
